---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/jrm-ui/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/jrm-service/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "docker"
    directory: "/jrm-service/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "docker"
    directory: "/jrm-ui/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "friday"
